version: 2
updates:
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'daily'
  groups:
    artifacts:
      patterns:
      - "*-artifact"

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
